### ISSUE TITLE
Web client doesn't load, stuck at decrypting.

### ISSUE THREAD

**Issue by QazCetelic** [meganz/webclient#116]
![image](https://user-images.githubusercontent.com/51381523/185392976-5a3e94dc-73bb-44ab-8e5c-b520d7a6c2d5.png)

14:20 opened application
14:55 still loading
15:57 still loading

**Comment by jx-mega** [comment]
Hello, we would like to look into your account status further, please email us at support@mega.nz from your MEGA account email address with the screenshot explaining your issue and we will help you from there!
