### ISSUE TITLE
Use EXIF metadata for galleries

### ISSUE THREAD

**Issue by BonaBeavis** [meganz/webclient#118]
The photo library in the web app right now is very bare bones.
Are there any plans to support EXIF tags for organizing photos into collections?

**Comment by jx-mega** [comment]
Hello,

Thank you for your email. 

Your suggestion is already in our roadmap, and it will be added to our services in future releases.

Have a MEGA-awesome day and contact us should you need any other assistance.

We appreciate all feedback and are working to improve and integrate new features with this feedback in mind.

**Comment by BonaBeavis** [comment]
That is great, do you have a timeline for this?
