### ISSUE TITLE
Undecrypted folder

### ISSUE THREAD

**Issue by Ronnie2309** [meganz/webclient#133]
Hi,

I can't access my all data due to folder showing Undecrypted folder!
to the past days even i can't open my account because of account stuck on decrypting page
my data is too important for me and don't have any hard backup
i trusted "mega.nz" that's why i didn't take any hard backup
now i'm in depression and got 3 time Anxiety attacks in that days feeling hopeless. 😞

Please help ASAP!

Check the pictures down below 👇

(Undecrypted folder!)
![image_89](https://github.com/meganz/webclient/assets/146136279/fcbf4e7f-c3ea-4723-8b3f-942412987338)

(Account stuck on this page)
![image_90](https://github.com/meganz/webclient/assets/146136279/ee2806d2-6d79-4fba-941f-3e4d9db2af46)

(What's that happening with my account and my precious data)
![image_91](https://github.com/meganz/webclient/assets/146136279/d7527d88-f4d5-4408-9e05-161fcb2ef61e)

(When i try to transfer my folder to another account)
![image_92](https://github.com/meganz/webclient/assets/146136279/d63ed4c9-cd25-4543-96e9-04154521de99)

(Try to login through mobile app)
![Screenshot_2023-09-28-13-28-54-30](https://github.com/meganz/webclient/assets/146136279/a7c421dd-797b-4532-905b-c4dc9baefa55)

**Comment by diegocr** [comment]
Hello @Ronnie2309, apologies for the inconvenience.

Please open the hamburger menu in the upper right side of the page and from there do click "Reload your account"

If that doesn't resolves it, please contact `support@mega.nz` for further assistance.

**Comment by Ronnie2309** [comment]
Hi @diegocr thanks for your reply.

I already did this "Reload your account" but still i can't access my data

I've already contacted on support@mega.nz too and I'm still waiting for their reply.

**Comment by diegocr** [comment]
Well, usually such a menu->reload does help to resolve this kind of issue (btw, you can hold the `ctrl`-key while clicking it to enforce a hard server-side reload, which may does help further)

It could also be that you did triggered a bug by the fact you're by far exceeding the account storage quota, so hopefully the support/help-desk team will help you on resolving this.

**Comment by Ronnie2309** [comment]
Hi, 

Thanks @diegocr for giving your valuable time for this issue,
yes i did  reload with ctrl-key but nothing changes,
I'm still waiting for their reply but no one is there for help me on this serious issue,
I'm too depressed, under stress and disappointed.

**Comment by DonaldTPP** [comment]
I lost 5TB of data because of this same problem.

**Comment by DonaldTPP** [comment]
Now what is happening is it's telling me different things every time I log in.

Saying what I've uploaded isn't where it was uploaded and it's also telling me I've used the space but there isn't that much content in the folders.

**Comment by Ronnie2309** [comment]
Hi @DonaldTPP
Sorry to hear that you lost your 5TB precious data,
i can understand because only who has gone through it can understand it,

fortunate support team help me to Successfully decrypted and now i can access my all data,
i am very very grateful and extremely thanks to all mega support and developers team
who gave me back my data access.

And special thanks to @diegocr who connected with me on this topic and try to help me in better posible way.


@DonaldTPP 
Follow my steps hope it will help you or others to recover your data by support team in single email it will take less time to make them understand and explaining.

1- Open text pad and start writing carefully what was happening with your data with date and time if possible.
2- Now login to your account on laptop or pc.
3- Once you login successfully then double-click on the affected folder and select the mega.nz/fm URL in full from the address bar.
4- Copy only the top-level URL, as everything underneath is automatically included.
5- Each link should look like this: https://mega.nz/fm/XXXXXXXX - where the last 8 digits/letters will be different for each folder.
6- This is the right time to write email to support team.
7- Now go to your account click on menu 3 dot located on upper right corner then support/Get Support/subject/Missing or invisible data.
8- Now copy all text from text pad were you wrote and paste in message box.
9- If you are a pro customer then don't forget to mention them your account type.
10- finally click on submit.

That's it,

Within a hour you'll got auto generated email from support team.


Hope it will helps you.

Thanks.

God bless you all aways...

**Comment by gabianastasie** [comment]
@Ronnie2309 Boycott MEGA! [https://web.archive.org/web/20231101003041/https://github.com/meganz/webclient/issues/135](https://web.archive.org/web/20231101003041/https://github.com/meganz/webclient/issues/135)

MEGA desperately tries to cover up abuse. MEGA even deleted the above-mentioned post, but we used archive.org to save it.

Don't give your money to low-down individuals that harm a mentally ill person. Don't associate yourself with such scoundrels.
