### ISSUE TITLE
Problems over unencrypted folder

### ISSUE THREAD

**Issue by gabrielrovesti** [meganz/webclient#136]
I have an access to a shared folder, in which there are multiple users asking for share.

After being accepted to the folder, people coming inside find the "Decrypted error" and "Decrypted folder", in which files are all null or unseen and invisible, as you can see from the image.

![Immagine 2023-11-10 142918](https://github.com/meganz/webclient/assets/95100089/69791d94-163e-433c-b82b-a2c0bb88e5f1)

What can be the possible solutions?

**Comment by diegocr** [comment]
Hello @gabrielrovesti, apologies for the inconvenience.

There might be a few reasons for them to be undecryptable, what i would suggest to try first as a solution is that each one of you do verify the credentials of each other, and then you all could try to open the hamburger menu in the upper right side of the page and from there do click on "Reload your account" while holding down the ctrl-key.

If that doesn't resolves it, please contact support@mega.nz for further assistance.

**Comment by gabrielrovesti** [comment]
Thank you, it seems to be working. Some common methods I saw working before were: deleting cache, deleting cookies, going incognito or something. Usually these methods seemed to be working, but yours is working as of now, thank you so much really. What can be the cause anyway, I don't know if it's related to MEGA itself and its policy in key handling and stuff.

**Comment by diegocr** [comment]
Pleased to hear that resolved it!

Answering your question about the cause, unless you did stumble on an actual bug, we could tell that's just as result of the increased complexity towards improved security as we have revamped recently how sharing does work, you may read about this at https://blog.mega.io/e2ee-security-update/
