### ISSUE TITLE
"Clear rubbish bin" option empties the bin but space is still shown as used

### ISSUE THREAD

**Issue by Knitter** [meganz/webclient#14]
I had several sync debris in my account's rubbish bin; about 12% of my total space. After deleting everything, it still shows the space as used. I keep clearing the debris whenever the sync client creates them but both my dashboard info and the MegaSync client show the space used by the rubbish bin.

I'm using Firefox 51.0.1, 64bit, on macOS sierra, and MegaSync for macOS.

**Comment by diegocr** [comment]
Please contact support[a]mega.nz if this is still an issue.
