### ISSUE TITLE
indexedDB.webkitGetDatabaseNames() is deprecated and will be removed from Chrome

### ISSUE THREAD

**Issue by inexorabletash** [meganz/webclient#16]
Just a heads-up that per https://www.chromestatus.com/features/5725741740195840 we're planning on removing the non-standard indexedDB.webkitGetDatabaseNames() API from Chrome in M60, around August 2017.

It looks like your code will handle this properly since it already functions on other browsers, but I wanted to check in and ensure that this deprecation timeline will not have any unforeseen impact.

**Comment by diegocr** [comment]
Thanks for bringing that to our attention, certainly we have had a polyfill for quite some time that prevented any issue from the deprecation.
