### ISSUE TITLE
Errors are not correctly reported

### ISSUE THREAD

**Issue by PascalTemel** [meganz/webclient#37]
![image](https://user-images.githubusercontent.com/13536271/45933615-ce2c3680-bf90-11e8-9bb0-c13bda13ef21.png)

Actual error: 
![image](https://user-images.githubusercontent.com/13536271/45933625-ff0c6b80-bf90-11e8-9294-e3861501f8c7.png)

Happened to me while skipping through a video and I was able to reproduce it.

I'm not sure whether this is the correct repository - sorry if it isn't.

**Comment by diegocr** [comment]
Thanks for bringing that to our attention, we have [now fixed](https://github.com/meganz/videostream/commit/74113d09beb4e3f86fde96f6045f8fe57704ee87) the issue.
