### ISSUE TITLE
Request: pdf preview

### ISSUE THREAD

**Issue by Gaboose** [meganz/webclient#4]
I'm using Mega to archive a lot of documents. I would love if Mega web client had a pdf preview mechanism, like in the screenshots of Google Drive, Dropbox and Copy.com below. It would make browsing and sharing docs so much easier.

![Google Drive](http://i.imgur.com/8oy39Mm.png)
![Dropbox](http://i.imgur.com/I4pcevV.png)
![Copy.com](http://i.imgur.com/48BezTY.png)

**Comment by camilokawerin** [comment]
+1 to this request. I grid view with thumbnails would be really nice too.

**Comment by camilokawerin** [comment]
Thanks @cr-nz !
