### ISSUE TITLE
Keyboard shortcuts and video playback UX

### ISSUE THREAD

**Issue by danielfazlijevic** [meganz/webclient#41]
Hey everyone, is there a way to disable shortcuts like CTRL + 1, CTRL + 2 and CTRL + 3?
For example, I sometimes play videos hosted on Mega and use these shortcuts for navigating between tabs, instead it seeks the video player to certain points of the video which is annoying.
To make the things worse, if the background of the video controls is white, times are basicly invisible. 
I suggest applying a mild background gradient as a background on video controls.

**Comment by diegocr** [comment]
Thanks for the feedback, we will look into it.
