### ISSUE TITLE
It's a yes from me ! 👍

### ISSUE THREAD

**Issue by 1488777** [meganz/webclient#43]
It's a yes from me ! 👍

_Originally posted by @tigerblue77 in https://github.com/meganz/webclient/pull/39#issuecomment-456566280_

**Comment by tigerblue77** [comment]
Why does nobody merge this commit ? 🤣

**Comment by cr-nz** [comment]
Commented here https://github.com/meganz/webclient/pull/39#issuecomment-504251039
