### ISSUE TITLE
Guide remedy

### ISSUE THREAD

**Issue by Cutetlaem** [meganz/webclient#5]
I encountered this error: "An error occurred while loading MEGA. The file" http://eu.static.mega.co.nz/3/sjcl.js "is corrupt. Please try again later. We apologize for the inconvenience . " Now I want to fix how to do? Please reply me soon!

**Comment by cr-nz** [comment]
If running locally it's essential that your set the following localStorage parameters in the console:

```
// Path of your local development host.
localStorage.staticpath = 'http://localhost/mega/';

// Disables the cryptographic hash verification logic (it's not needed because you are running the code locally and not loading files from the CDN).
localStorage.dd = 1;
```

Try that and then refresh the page. Let me know if that doesn't work for you.

**Comment by Cutetlaem** [comment]
what?

**Comment by Cutetlaem** [comment]
@cr-nz Please going to web site of me! I need more help! Here is my website: Cloud.Yidx.Net! I do not understand how this code Installation!
