### ISSUE TITLE
Feature request: CR3 Raw images support

### ISSUE THREAD

**Issue by titivermeesch** [meganz/webclient#53]
Is there a way to add visualisation for raw picture files ?
I always shoot my photos in CR3 format and it would be great to visualise them directly in the mega client.

There are more raw image extensions here : https://en.wikipedia.org/wiki/Raw_image_format

Right now I have to download my folder and the sort the pictures that are on it (for those who were already uploaded in the past).

**Comment by diegocr** [comment]
We do support raw picture files using [dcraw.js](https://github.com/meganz/dcraw.js), but not the CR3 format yet.

The currently supported formats are as follow:

https://github.com/meganz/webclient/blob/ca87ae115dcb5f6359794e6e68aa813523ffc284/js/utils/media.js#L104-L132

We will look into adding CR3 support whenever possible.

**Comment by titivermeesch** [comment]
Would be great to have it supported, I can't use MEGA if CR3 is not supported

**Comment by diegocr** [comment]
Partial CR3 support is now available, allowing to extract the embed thumbnails on them to properly display/preview them in the web.
