### ISSUE TITLE
Can't clone the repository on local computer

### ISSUE THREAD

**Issue by valfur03** [meganz/webclient#58]
When I try to clone the repository on my computer, following the guide in the REAME.md (https://github.com/meganz/webclient#local-webclient-setup-instructions-for-ubuntu-for-megachat-see-installmd), I get the followin error: 
ssh: connect to host code.developers.mega.co.nz port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lpetrov** [comment]
the correct command to clone it from github is:
> git clone git@github.com:meganz/webclient.git webclient.local
