### ISSUE TITLE
[UI] add dark theme

### ISSUE THREAD

**Issue by strixaluco** [meganz/webclient#64]
As the title says, please add the dark theme option so that it's easier on the eyes to use MEGA in dark environments.
Thanks in advance.

**Comment by jkiess** [comment]
definite +1

**Comment by deadenduser** [comment]
All programs and websites should have a dark mode tbh.

**Comment by Celeste251** [comment]
+1

**Comment by maltesserver** [comment]
+1

**Comment by khaleddaifallah-mega** [comment]
Dark mode will be available soon. Planned to be released in mid-quarter of 2021.

**Comment by Alyndiar** [comment]
> Dark mode will be available soon. Planned to be released in mid-quarter of 2021.

Great! That was really missing from the extension :)

**Comment by zaki4t** [comment]
> 
> 
> Dark mode will be available soon. Planned to be released in mid-quarter of 2021.

Good news! Hope that is for perfection, the Firefox version of Dark Reader cannot gain access to the Mega extension & it's been a long way.

**Comment by ashgoodman** [comment]
Dark mode does not work with the browser extension in chrome.

**Comment by khaleddaifallah-mega** [comment]
Thank you for the feedback.
Currently, Extensions are not updated yet to V4. The new UI updates are planned to be rolled out to Extensions in 2nd quarter of 2021. 
Stay tuned 🙂

**Comment by wizard86pz** [comment]
Woo, so this is the last month of 2nd quarter :) Thanks for info.

**Comment by wizard86pz** [comment]
Great to see that the Chrome extension has been updated with dark mode @khaleddaifallah-mega, thanks.

**Comment by khaleddaifallah-mega** [comment]
Done
