### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by Trylek12** [meganz/webclient#7]
npm ERR! phantomjs-prebuilt@2.1.12 install: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.12 install script.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

**Comment by Trylek12** [comment]
Fixed

**Comment by VenkateshKatabathula** [comment]
Please let me know how this issue was fixed...!!!
