### ISSUE TITLE
UX - Double-click on non-playable files triggers download

### ISSUE THREAD

**Issue by pilsnerbeer** [meganz/webclient#75]
Please consider this suggestion:

User doesn't know which files are playable via the web app and which aren't. (For instance, mp4s are but .mkv arent.) However, there is no difference between playable and non-playable files on the UI part as both files have same visual infographics about them (both length and thumbnail are shown.)  If user double-clicks on a playable file, the video plays in the webapp (expected.) However, for non-playable media, it immediately starts downloading to PC. This should not happen - first inform the user that the video is not playable in web and then offer an option to download it (via dialogue window?).

If a video is not playable via webUI, I might want to stream it instead or simply skip watching it. I am not directly asking for it to be downloaded just by double-clicking it.

**Comment by pilsnerbeer** [comment]
My current workaround is to right-click every videofile to see if there's a 'Play Video' option in the menu. If there isn't, I know it is not playable and I better stream it instead.

**Comment by sakethv-mega** [comment]
Hello there, we have passed on your feedback to our web client team. Thank you.
