### ISSUE TITLE
[BUG]: "Converstations" panel is being served using the development build of React

### ISSUE THREAD

**Issue by coopslarhette** [meganz/webclient#76]
when opening the Conversations panel of the client, nothing is minified and React Development Tools warns that the page is using the development build of React

![Screen Shot 2021-03-07 at 11 54 07 AM](https://user-images.githubusercontent.com/23089508/110253011-ee6fc600-7f3c-11eb-9849-79f64969f4af.png)

sorry if this is as intended, or has been previously reported.

**Comment by lpetrov** [comment]
Its intentional. We generally try to keep code readable, to ease anyone who wants to debug/read/audit our public code (in the end... MEGA is the privacy company). Thats the reason, why we keep the React dev build at the moment :)
