### ISSUE TITLE
Thumbnails of h265 videos are not generated

### ISSUE THREAD

**Issue by epdev** [meganz/webclient#77]
I've tested another formats: h264, vp9, av1 and thumbnails are generated there. Thumbnails on h265 videos used to work in the past so it probably has nothing to do with lack of browsers support of h265 decoding.

**Comment by sakethv-mega** [comment]
Hello there,

Can you please advise what browser and version are you using? We do support H.265 for browsers natively supporting hardware decoding for it, i.e. currently Safari 13+ however there is a current live Safari bug (video is not drawn onto the canvas - their devs have to fix it) - You can read more about it here: https://bugs.webkit.org/show_bug.cgi?id=206812

Thank you.

**Comment by epdev** [comment]
I tested on the newest Chrome and Edge. I know these browsers do not support h265 playback but is this expected that thumbnails are not generated for h265 videos on these browsers? I think it used to work in the past.

**Comment by diegocr** [comment]
We do need playback support in the browser(s) to be able to generate thumbnails.

I think it's very possible this used to work for you in the old Edge (non-Chromium based), check whether what is explained here does help: https://techcommunity.microsoft.com/t5/discussions/hevc-support-for-chromium-edge/m-p/1439093
