### ISSUE TITLE
Always a new notification for a new message chat received

### ISSUE THREAD

**Issue by wizard86pz** [meganz/webclient#79]
Every time I access to web app ([last version](https://github.com/meganz/webclient/releases/tag/v3.119.0) on Google Chrome 90.0.4430.93 and Safari 14.1 (16611.1.21.161.6)), I always see the new message notification on the left column side.

![image](https://user-images.githubusercontent.com/36189429/117000824-eedcd100-ace1-11eb-960b-bdcbbda9b030.png)

The chat is synced in the web app and no problem using it. But this keeps occurring even if I simply read the chat from the web, the notification icon correctly disappear and i log out: at the next log in, I'll continue to see that notification for the same chat.

**Comment by lpetrov** [comment]
Hi there,
Thanks for helping us making the MEGA's webclient better, by reporting this :)

Few questions to help us replicate this:
1) What type are the messages shown as unread? (normal text, call related, attachment, etc)
2) Are they in the same chat room?
3) Are there any errors in the console after you open the chats and mark the messages as read again? If yes, can you send those to https://mega.nz/support with a reference to this issue please

Thanks!
Lyubomir

**Comment by wizard86pz** [comment]
1. I see the amount of unread messages always only in a single chat. I have a total of 3 chats, and it happens ONLY in a single chat. The chat does not receive new messages, so I cannot tell you exactly which type of messages are wrongly generating the notification icon on the chat icon shown in the report.
2. yes, the unread messages are only from a single chat.
3. I see some error in che Chrome console switching from a chat, to another. I collected the logs once I open the chat to clear the unread amount of messages and switch to another one. Gonna be sent to the email you mentioned, mentioning the issue link https://github.com/meganz/webclient/issues/79#

Thanks for help.

**Comment by wizard86pz** [comment]
@lpetrov, I've just sent the report, via https://mega.nz/support

**Comment by lpetrov** [comment]
Log received.
But not it didn't contained much ideas for me to figure out the issue.

Can you do the following:
1) Log out
2) Write in the console:
> localStorage.d = 1; localStorage.chatdLogger = 1;
3) Refresh the page
4) Log in
5) Go to that chat that says there are unread messages and open it (that would clear the unread counter)
6) Right click in the console -> Save as, save the file and email it support@mega.nz (since the file may be too big to paste in the form I provided earlier)

Thanks! :)

**Comment by wizard86pz** [comment]
@lpetrov, email just sent.

**Comment by lpetrov** [comment]
<img width="473" alt="Screen Shot 2021-05-05 at 12 49 19 AM" src="https://user-images.githubusercontent.com/139877/117074858-9981dd80-ad3c-11eb-81f4-405bfacdb0de.png">

Sorry, but can you redo the same steps with all from the screenshot checked.
E.g. In the console window, click "All levels" dropdown and mark all except "Default" - Verbose, Info, Warnings and Errors
And resend the new log as a reply to the support email.

A potential fixes are:
- Try "Menu -> Reload your account"
- I saw you are using the extension...disabling the extension or removing it and reinstalling it may help

But those won't guarantee it won't happen again. I will log it as a bug and try to dig more, but still, a log would speed things up a bit :)

Thanks!

**Comment by wizard86pz** [comment]
Hi,
I've tried the suggested potential fixes but not any change:

   - reloading the account, the unread amount is still there, all the times
   - I've used an anonymous Chrome window with no MEGA extension running.

I've tried from Firefox too, with MEGA extension, from a different build of
MEGA web app: 3.117.14: but still same issue.

I've enabled all the levels of the console log, except the "Default". You
can find the log attached.

Il giorno mer 5 mag 2021 alle ore 00:00 Lyubomir Petrov <
***@***.***> ha scritto:

**Comment by lpetrov** [comment]
![image](https://user-images.githubusercontent.com/139877/117113292-f0b29d00-ad92-11eb-93ec-601d50430b95.png)

Can you redo the same steps with all from the screenshot checked?
E.g. In the console window, click "All levels" dropdown and mark all except "Default" - Verbose, Info, Warnings and Errors
And resend the new log as a reply to the support email.

**Comment by wizard86pz** [comment]
It's what I've done already, Lyubomir. Something missing in the -99014.log
file sent in previous email?

I've done these steps:

   1. Log out
   2. Refresh the page.
   3. Log in
   4. Go to that chat that says there are unread messages and open it (that
   would clear the unread counter)
   5. Right click in the console -> Save as, save the file and email it
   ***@***.*** (since the file may be too big to paste in the form I
   provided earlier)

I've not re-typed "localStorage.d = 1; localStorage.chatdLogger = 1" since
for what I see, it was already active, or should I have re-typed the
command in the console?

Il giorno mer 5 mag 2021 alle ore 10:14 Lyubomir Petrov <
***@***.***> ha scritto:

**Comment by lpetrov** [comment]
Yeah, the log didn't included "Verbose" messages, since they were filtered by that feature in the dev tools.
So, basically once those are enabled as in the screenshot I'd provided and steps redone, the log would contain the complete data where the client tries to mark the messages as read :)

**Comment by wizard86pz** [comment]
Ok, I've done and sent as attachment in an email.

**Comment by lpetrov** [comment]
Sorry for the delay, it had been a busy days (even on the weekend).
I got the log and I'm discussing it internally with some other team members, since from the log, it seems ok at first, but we would check few more stuff to try to figure it out :)

**Comment by lpetrov** [comment]
Hello there.
We found the core issue and it should be fixed. 
Let us know if it works for you :)

Thanks!
Lyubomir

**Comment by wizard86pz** [comment]
Great, thanks. I'm waiting for the MEGA app CHrome extension update, to have the 4.0.6 web app to test.

**Comment by lpetrov** [comment]
The fix was server side related, so it should work no matter the client version :)

**Comment by wizard86pz** [comment]
Even better, I'll check in coming hours/days. Thanks.

**Comment by wizard86pz** [comment]
It seems solved, at least with the chat that I've always used to reproduce the issue, thank server side team.
