### ISSUE TITLE
sg.static.mega.co.nz lacks IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [meganz/webclient#83]
The Singapore static server (sg.static.mega.co.nz) lacks IPv6 addresses and thus resources from it can't be received using IPv6.

Is it possible to enable IPv6 for Singapore static server since IPv6 is available for other static server (EU, NA, NZ)?

Thank you.

**Comment by sakethv-mega** [comment]
Hello, our sys admins have confirmed that the ipv6 addresses have now been added. Please try aagin. Thank you.
