### ISSUE TITLE
All programs and websites should have a dark mode tbh.

### ISSUE THREAD

**Issue by AlleVVatoR** [meganz/webclient#87]
All programs and websites should have a dark mode tbh.

_Originally posted by @deadenduser in https://github.com/meganz/webclient/issues/64#issuecomment-789174453_

**Comment by AlleVVatoR** [comment]
!!!!!!!!

**Comment by AlleVVatoR** [comment]
I Licke it!

**Comment by AlleVVatoR** [comment]
Goode!

**Comment by Barraguesh** [comment]
This already happening, the mobile app plus web interface have dark mode. The desktop app lacks it, but I'm sure it's in the pipeline, please don't spam inside issues as it makes it more troll-y than useful.
