### ISSUE TITLE
Files are not beeing displayed

### ISSUE THREAD

**Issue by MrYingNYang** [meganz/webclient#95]
I came across the problem that the webclient with and without the extension does not show all files in each folder. This bug only happens on large data sets. Meaning the total amount of data that is uploaded to the server. I got about 1TB of data in the cloud. 
All folders are beeing displayed but the files that are in these folders are not visible. Metadata indicates that the files are indeed existing in the folder. When I use the search function to search fot one of these files then the file will not be found. Also when the folder is sync'd to a device the files are beeing downloaded.

**Comment by khaleddaifallah-mega** [comment]
Hi,
From the right side menu, do  a full account reload. this might be a caching issue. Please advise if the issue is resolved after.
<img width="237" alt="image" src="https://user-images.githubusercontent.com/34146365/138193237-5adb8a19-4800-4756-8820-6ddd606cc1e4.png">
